# Generated by Django 4.2.6 on 2024-08-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/post-covers'),
        ),
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
