# Generated by Django 4.2.6 on 2023-10-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_utilisateur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
