# Generated by Django 4.2.6 on 2023-10-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgpul_admin', '0003_alter_matiere_enseigne_par_and_more'),
        ('utilisateur', '0004_alter_utilisateur_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgpul_admin.departement'),
        ),
    ]
