# Generated by Django 4.2.6 on 2024-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_utilisateur_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant')], default='etudiant', max_length=10),
        ),
    ]
