# Generated by Django 4.2.6 on 2025-08-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_utilisateur_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant')], max_length=10),
        ),
    ]
