# Generated by Django 4.2.6 on 2023-11-04 23:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.SmallIntegerField(choices=[(1, 'Actif'), (2, 'Supprimer')], default=1)),
                ('nom_dept', models.CharField(max_length=50)),
                ('code_dept', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('statut', models.SmallIntegerField(choices=[(1, 'Actif'), (2, 'Supprimer')], default=1)),
                ('genre_ens', models.SmallIntegerField(choices=[(1, 'Féminin'), (2, 'Masculin')])),
                ('tel_ens', models.CharField(max_length=12)),
                ('specialite_ens', models.CharField(max_length=40)),
                ('adresse_en', models.CharField(max_length=30)),
                ('photo_ens', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('utilisateur.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.SmallIntegerField(choices=[(1, 'Actif'), (2, 'Supprimer')], default=1)),
                ('nom_mat', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('classe_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_de_matiere', to='pgpul_admin.classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matiere_created_by', to=settings.AUTH_USER_MODEL)),
                ('dept_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_matiere', to='pgpul_admin.departement')),
                ('enseigne_par', models.ManyToManyField(blank=True, related_name='matiere_enseigne_par', to='pgpul_admin.enseignant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matiere_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='supportCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.SmallIntegerField(choices=[(1, 'Actif'), (2, 'Supprimer')], default=1)),
                ('designation_support', models.FileField(upload_to='documents', verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cours_created_by', to=settings.AUTH_USER_MODEL)),
                ('matiere_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_matiere', to='pgpul_admin.matiere')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cours_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.SmallIntegerField(choices=[(1, 'Actif'), (2, 'Supprimer')], default=1)),
                ('nom_fac', models.CharField(max_length=50)),
                ('code_fac', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculte_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculte_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=15, unique=True)),
                ('genre_etd', models.SmallIntegerField(choices=[(1, 'Féminin'), (2, 'Masculin')])),
                ('tel_etd', models.CharField(max_length=12)),
                ('photo_ens', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_created_by', to=settings.AUTH_USER_MODEL)),
                ('departement_etd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_de_etudiant', to='pgpul_admin.departement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('utilisateur.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='dept_fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgpul_admin.faculte'),
        ),
        migrations.AddField(
            model_name='departement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
