# Generated by Django 4.2.5 on 2023-10-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('userinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pgpul_admin.userinfos')),
                ('designation', models.CharField(max_length=40, unique=True)),
            ],
            bases=('pgpul_admin.userinfos',),
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('userinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pgpul_admin.userinfos')),
                ('nom_dept', models.CharField(max_length=50)),
                ('code_dept', models.IntegerField(unique=True)),
            ],
            bases=('pgpul_admin.userinfos',),
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('userinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pgpul_admin.userinfos')),
                ('nom_fac', models.CharField(max_length=50)),
                ('code_fac', models.IntegerField(unique=True)),
            ],
            bases=('pgpul_admin.userinfos',),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('userinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pgpul_admin.userinfos')),
                ('nom_mat', models.CharField(max_length=40)),
            ],
            bases=('pgpul_admin.userinfos',),
        ),
        migrations.CreateModel(
            name='supportCours',
            fields=[
                ('userinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pgpul_admin.userinfos')),
                ('designation_support', models.FileField(upload_to='documents', verbose_name='')),
            ],
            bases=('pgpul_admin.userinfos',),
        ),
    ]
