# Generated by Django 4.2.5 on 2023-10-17 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgpul_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportcours',
            name='matiere_support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgpul_admin.matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe_mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgpul_admin.classe'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='dept_mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgpul_admin.departement'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseigne_par',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='dept_fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculte_departement', to='pgpul_admin.faculte'),
        ),
    ]
