# Generated by Django 4.2.6 on 2023-11-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgpul_admin', '0002_classe_created_at_classe_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='departement_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_principal_enseignant', to='pgpul_admin.departement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='departements_enseigne',
            field=models.ManyToManyField(related_name='departements_enseigne_enseignant', to='pgpul_admin.departement'),
        ),
    ]
