# Generated by Django 4.2.6 on 2023-10-29 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgpul_admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='enseigne_par',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
